### ISSUE TITLE
How to deel with "Py4JNetworkError"?

### ISSUE THREAD

**Issue by YMMS** [py4j/py4j#123]
Hi, everybody here. 
I got a problem when I tried the example code of "py4j".

The code is as follow:
          from py4j.java_gateway import JavaGateway
          gateway = JavaGateway()
          random = gateway.jvm.java.util.Random()

The error information is as follow:
          Traceback (most recent call last):
              File "C:\Users\YM_MS\Desktop\py4j_new_test.py", line 3, in <module>
              random = gateway.jvm.java.util.Random()
          File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 708, in **getattr**
    '\n' + END_COMMAND_PART)
          File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 339, in send_command
              connection = self._get_connection()
          File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 295, in _get_connection
              connection = self._create_connection()
          File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 302, in _create_connection
              connection.start()
          File "C:\Python27\lib\site-packages\py4j\java_gateway.py", line 409, in start
              raise Py4JNetworkError(msg)
Py4JNetworkError: An error occurred while trying to connect to the Java server

How to deal with this error?

Thanks!

**Comment by e12047** [comment]
Hi, I'm new to Py4J. I've already stared the java server and still when I run the python code, it gives "Py4JNetworkError: An error occurred while trying to connect to the Java server"
Thanks in advance for any help

**Comment by bartdag** [comment]
@e12047 please use the mailing list https://groups.google.com/a/py4j.org/forum/#!forum/py4j/join for support questions. In your case, did you start the JVM first?

**Comment by e12047** [comment]
yes.
