### ISSUE TITLE
Default arguments not possible in Scala methods

### ISSUE THREAD

**Issue by fractus** [py4j/py4j#326]
Hi, 

I still haven't figured out a way to call a Scala method that has default arguments, although they are reflected in the Python side, but with non-compliant names. For example, 

```scala 
package util

import py4j.GatewayServer

class EntryPoint

object PythonGateway {

  def main(args: Array[String]): Unit = {
    val gatewayServer = new GatewayServer(new EntryPoint)
    gatewayServer.start()
    System.out.println("Gateway Server Started")
  }

  def withDefaults(a: Int = 2, b: String = "AA"): String = s"$a -> $b"
}
```

```python
In [1]: from py4j.java_gateway import JavaGateway

In [2]: g = JavaGateway()

In [3]: PythonGateway = g.jvm.util.PythonGateway

In [4]: dir(PythonGateway)
Out[4]:
['withDefaults',
 'withDefaults$default$1',
 'withDefaults$default$2']

In [5]: PythonGateway.withDefaults(99, "ZZ")
Out[5]: '99 -> ZZ'
```
The methods with the `$` sign can be called and they return the value of defaults, but the method can't be called with one or zero args; 
```Python
In [8]: getattr(PythonGateway, 'withDefaults$default$1')()
Out[8]: 2

In [9]: PG.withDefaults(2)
---------------------------------------------------------------------------
Py4JError                                 Traceback (most recent call last)
<ipython-input-9-3a0efa78ba1b> in <module>()
----> 1 PG.withDefaults(9)

C:\tools\anaconda3\lib\site-packages\py4j\java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258
   1259         for temp_arg in temp_args:

C:\tools\anaconda3\lib\site-packages\py4j\protocol.py in get_return_value(answer, gateway_client, target_id, name)
    330                 raise Py4JError(
    331                     "An error occurred while calling {0}{1}{2}. Trace:\n{3}\n".
--> 332                     format(target_id, ".", name, value))
    333         else:
    334             raise Py4JError(

Py4JError: An error occurred while calling z:util.PythonGateway.withDefaults. Trace:
py4j.Py4JException: Method withDefaults([class java.lang.Integer]) does not exist
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
        at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:339)
        at py4j.Gateway.invoke(Gateway.java:276)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)

```

Thanks

Ps. This is run on Windows 10 with Java 1.8.0_172, Scala 2.11.8, Python 3.6.5 64 bit and py4j 0.10.7

**Comment by tobegit3hub** [comment]
We have the similar problem with `py4j` to call Scala's functions or constructors with default parameters.

It seems to be the limitation of `py4j` and I'm not sure if we can fix it in the future or not. @bartdag

**Comment by bartdag** [comment]
Hi,

Sorry, I have little experience with Scala. My understanding is that Scala creates multiple declarations of the method and chooses at compile time which method to call depending on the number of arguments at the call site.

Py4J would have to determine at runtime which method to call. Unless the Scala compiler exposes some utilities to help with that, I think this has the scope of an entire project or module.

See https://lampwww.epfl.ch/~michelou/scala/using-scala-from-java.html for why calling methods with default arguments is difficult even from Java.

**Comment by tobegit3hub** [comment]
Thanks @bartdag  and it is reasonable to me. Since Java does not support default parameters for methods, Scala has its implementation which requires Java to call with extra specification. `py4j` may not do more than what `Java` has supported.

We has fixed this by defining multiple methods without default parameter in Java way. Maybe @fractus can do that as well.
