### ISSUE TITLE
Iterating through immutable lists returned from Java

### ISSUE THREAD

**Issue by karmalis** [py4j/py4j#504]
Suppose you have a function within Java which returns an immutable list. As simple as 
```java
class Test {
    public static List<Integer> anImmutableList() {
        return List.of(1);
    }
}
```
And you attempt to get that list, plus later on iterate through it:
```python
test_list = java_gateway.Test.anImmutableList()
result = [ it + 1 for it in test_list]
```
Then a `Py4JError` is returned whenever it is attempted to iterate through the list:
```
py4j.protocol.Py4JError: An error occurred while calling o1093.iterator. Trace:
java.lang.reflect.InaccessibleObjectException: Unable to make public java.util.Iterator java.util.ImmutableCollections$AbstractImmutableList.iterator() accessible: module java.base does not "opens java.util" to unnamed module @417bda74
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at py4j.reflection.MethodInvoker$1.run(MethodInvoker.java:240)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:238)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

At the time of writing Java 17 and py4j 0.10.9.7 is used. 

Is this an actual bug or am I missing something? Somehow this works very counter intuitive (one needs to create a mutable list forcefully, which then introduces code style and quality issues)

**Comment by HyukjinKwon** [comment]
Seems like we should fix, yes.

**Comment by karmalis** [comment]
I have found another thing which I believe might be related and could possibly help you out. 

Given the same test function in Java (version 17), but slightly altered:
```java
class Test {
    public static List<Integer> aMutableList() {
        var result = new ArrayList<Integer>();
        result.add(42);
        return result;
    }
}
```
And calling the function within python (version 0.10.9.7):
```python
test_list = java_gateway.Test.aMutableList()
```
Then the following can be observed
```python
from pprint import pprint

print(len(test_list)) # will display 1
print(test_list[0]) # will display 42
pprint(test_list) # will display []

another_list = [i + 1 for i in test_list]
print(len(another_list)) # will display 0
```
No exceptions or errors are observed, but the behavior is that it is not possible to access list items by iterating through them.
There is a workaround, however:
```python
another_list = []
for i in range(0, len(test_list)):
    another_list.append(test_list[i] + 1)
print(len(another_list)) # will display 1
```

Hope this helps
